"""
Meteorological Layer Catalog & Taxonomy.
Defines all 10 meteorological categories and their layer configurations,
units, physical ranges, colormap palettes, and scientific descriptions.
"""

from typing import Any, Dict, List


METEOROLOGICAL_LAYERS: List[Dict[str, Any]] = [
    # 1. PRECIPITATION
    {
        "id": "total_precipitation",
        "name": "Total Precipitation",
        "category": "Precipitation",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 150,
        "description": "Total accumulated precipitation rate over 24-hour forecast window.",
        "icon": "CloudRain",
    },
    {
        "id": "rain_rate",
        "name": "Rain Rate",
        "category": "Precipitation",
        "units": "mm/h",
        "palette": "rain",
        "min": 0,
        "max": 25,
        "description": "Instantaneous rainfall intensity rate.",
        "icon": "CloudDrizzle",
    },
    {
        "id": "convective_precipitation",
        "name": "Convective Precipitation",
        "category": "Precipitation",
        "units": "mm/day",
        "palette": "convective",
        "min": 0,
        "max": 100,
        "description": "Subgrid convective precipitation from cumulus parameterization.",
        "icon": "CloudLightning",
    },
    {
        "id": "accum_1h",
        "name": "1h Accumulation",
        "category": "Precipitation",
        "units": "mm",
        "palette": "rain",
        "min": 0,
        "max": 30,
        "description": "1-hour accumulated precipitation volume.",
        "icon": "Clock",
    },
    {
        "id": "accum_3h",
        "name": "3h Accumulation",
        "category": "Precipitation",
        "units": "mm",
        "palette": "rain",
        "min": 0,
        "max": 50,
        "description": "3-hour accumulated precipitation volume.",
        "icon": "Clock",
    },
    {
        "id": "accum_6h",
        "name": "6h Accumulation",
        "category": "Precipitation",
        "units": "mm",
        "palette": "rain",
        "min": 0,
        "max": 80,
        "description": "6-hour synoptic precipitation accumulation.",
        "icon": "Clock",
    },
    {
        "id": "accum_12h",
        "name": "12h Accumulation",
        "category": "Precipitation",
        "units": "mm",
        "palette": "rain",
        "min": 0,
        "max": 120,
        "description": "12-hour diurnal precipitation accumulation.",
        "icon": "Clock",
    },
    {
        "id": "accum_24h",
        "name": "24h Accumulation",
        "category": "Precipitation",
        "units": "mm",
        "palette": "rain",
        "min": 0,
        "max": 200,
        "description": "24-hour daily rainfall accumulation.",
        "icon": "Clock",
    },
    {
        "id": "accum_48h",
        "name": "48h Accumulation",
        "category": "Precipitation",
        "units": "mm",
        "palette": "rain",
        "min": 0,
        "max": 350,
        "description": "48-hour 2-day storm accumulation.",
        "icon": "Clock",
    },
    {
        "id": "accum_72h",
        "name": "72h Accumulation",
        "category": "Precipitation",
        "units": "mm",
        "palette": "rain",
        "min": 0,
        "max": 500,
        "description": "72-hour 3-day monsoon spell accumulation.",
        "icon": "Clock",
    },
    {
        "id": "prob_heavy_rain",
        "name": "Heavy Rainfall Probability (>25mm)",
        "category": "Precipitation",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "GEFS Ensemble probability of precipitation exceeding 25 mm/day (IMD Heavy Rain criterion).",
        "icon": "AlertTriangle",
    },
    {
        "id": "prob_extreme_rain",
        "name": "Extreme Rainfall Probability (>100mm)",
        "category": "Precipitation",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "GEFS Ensemble probability of precipitation exceeding 100 mm/day (IMD Very Heavy / Extreme).",
        "icon": "AlertOctagon",
    },
    {
        "id": "prob_gt_10mm",
        "name": "Probability > 10 mm",
        "category": "Precipitation",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Probability of moderate rainfall exceeding 10 mm.",
        "icon": "Percent",
    },
    {
        "id": "prob_gt_25mm",
        "name": "Probability > 25 mm",
        "category": "Precipitation",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Probability of rainfall exceeding 25 mm.",
        "icon": "Percent",
    },
    {
        "id": "prob_gt_50mm",
        "name": "Probability > 50 mm",
        "category": "Precipitation",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Probability of rainfall exceeding 50 mm.",
        "icon": "Percent",
    },
    {
        "id": "prob_gt_100mm",
        "name": "Probability > 100 mm",
        "category": "Precipitation",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Probability of rainfall exceeding 100 mm.",
        "icon": "Percent",
    },

    # 2. TEMPERATURE
    {
        "id": "temp_2m",
        "name": "2m Temperature",
        "category": "Temperature",
        "units": "°C",
        "palette": "thermal",
        "min": 10,
        "max": 48,
        "description": "Air temperature at 2 meters above ground level.",
        "icon": "Thermometer",
    },
    {
        "id": "temp_max",
        "name": "Maximum Temperature",
        "category": "Temperature",
        "units": "°C",
        "palette": "thermal",
        "min": 15,
        "max": 50,
        "description": "Daily maximum surface air temperature (Tmax).",
        "icon": "Flame",
    },
    {
        "id": "temp_min",
        "name": "Minimum Temperature",
        "category": "Temperature",
        "units": "°C",
        "palette": "thermal",
        "min": 5,
        "max": 35,
        "description": "Daily minimum surface air temperature (Tmin).",
        "icon": "Snowflake",
    },
    {
        "id": "apparent_temp",
        "name": "Apparent Temperature",
        "category": "Temperature",
        "units": "°C",
        "palette": "thermal",
        "min": 15,
        "max": 52,
        "description": "Perceived temperature combining heat index and relative humidity.",
        "icon": "Sun",
    },
    {
        "id": "temp_anomaly",
        "name": "Temperature Anomaly",
        "category": "Temperature",
        "units": "°C",
        "palette": "diverging_temp",
        "min": -8,
        "max": 8,
        "description": "Departure from long-term climatological normal.",
        "icon": "Activity",
    },
    {
        "id": "freezing_level",
        "name": "Freezing Level",
        "category": "Temperature",
        "units": "m",
        "palette": "elevation",
        "min": 1500,
        "max": 6500,
        "description": "Altitude of 0°C isotherm above sea level.",
        "icon": "Mountain",
    },

    # 3. WIND
    {
        "id": "wind_10m_speed",
        "name": "10m Wind Speed",
        "category": "Wind",
        "units": "kts",
        "palette": "wind_jet",
        "min": 0,
        "max": 45,
        "description": "Horizontal wind speed at 10 meters above ground.",
        "icon": "Wind",
    },
    {
        "id": "wind_10m_direction",
        "name": "10m Wind Direction",
        "category": "Wind",
        "units": "deg",
        "palette": "cyclic",
        "min": 0,
        "max": 360,
        "description": "Wind direction bearing (0° North, 90° East, 180° South, 270° West).",
        "icon": "Compass",
    },
    {
        "id": "wind_gust",
        "name": "Wind Gust",
        "category": "Wind",
        "units": "kts",
        "palette": "wind_jet",
        "min": 0,
        "max": 65,
        "description": "Peak instantaneous 10m surface wind gust.",
        "icon": "Zap",
    },
    {
        "id": "wind_850hpa",
        "name": "850 hPa Wind (Somali Jet)",
        "category": "Wind",
        "units": "kts",
        "palette": "wind_jet",
        "min": 0,
        "max": 60,
        "description": "Low-level monsoon jet core speed and cross-equatorial southwesterly flow.",
        "icon": "Wind",
    },
    {
        "id": "wind_700hpa",
        "name": "700 hPa Wind",
        "category": "Wind",
        "units": "kts",
        "palette": "wind_jet",
        "min": 0,
        "max": 50,
        "description": "Lower-mid tropospheric wind speed and moisture transport at 700 hPa.",
        "icon": "Wind",
    },
    {
        "id": "wind_500hpa",
        "name": "500 hPa Wind",
        "category": "Wind",
        "units": "kts",
        "palette": "wind_jet",
        "min": 0,
        "max": 50,
        "description": "Mid-tropospheric steering wind speed at 500 hPa.",
        "icon": "Wind",
    },
    {
        "id": "wind_300hpa",
        "name": "300 hPa Wind (Tropical Easterly Jet)",
        "category": "Wind",
        "units": "kts",
        "palette": "wind_jet",
        "min": 0,
        "max": 80,
        "description": "Upper-tropospheric Tropical Easterly Jet (TEJ) speed at 300 hPa.",
        "icon": "Wind",
    },
    {
        "id": "wind_anomaly",
        "name": "Wind Anomaly",
        "category": "Wind",
        "units": "m/s",
        "palette": "diverging_wind",
        "min": -15,
        "max": 15,
        "description": "Zonal wind anomaly relative to monsoon normal.",
        "icon": "Navigation",
    },

    # 4. PRESSURE & ATMOSPHERE
    {
        "id": "mslp",
        "name": "Mean Sea-Level Pressure",
        "category": "Pressure & Atmosphere",
        "units": "hPa",
        "palette": "pressure",
        "min": 990,
        "max": 1020,
        "description": "Atmospheric pressure reduced to mean sea level.",
        "icon": "Gauge",
    },
    {
        "id": "surface_pressure",
        "name": "Surface Pressure",
        "category": "Pressure & Atmosphere",
        "units": "hPa",
        "palette": "pressure",
        "min": 600,
        "max": 1020,
        "description": "Atmospheric pressure measured at topographic surface.",
        "icon": "Gauge",
    },
    {
        "id": "geopotential_height",
        "name": "Geopotential Height",
        "category": "Pressure & Atmosphere",
        "units": "gpm",
        "palette": "elevation",
        "min": 100,
        "max": 12000,
        "description": "Geopotential height at selected isobaric level (1000-300 hPa).",
        "has_levels": True,
        "icon": "Layers",
    },
    {
        "id": "pressure_anomaly",
        "name": "Pressure Anomaly",
        "category": "Pressure & Atmosphere",
        "units": "hPa",
        "palette": "diverging_pressure",
        "min": -12,
        "max": 12,
        "description": "Synoptic MSLP departure from regional baseline.",
        "icon": "TrendingDown",
    },
    {
        "id": "relative_vorticity",
        "name": "Relative Vorticity",
        "category": "Pressure & Atmosphere",
        "units": "10^-5 s^-1",
        "palette": "diverging_vorticity",
        "min": -10,
        "max": 15,
        "description": "Vertical component of curl of horizontal velocity (cyclonic vs anticyclonic spin).",
        "icon": "RotateCw",
    },
    {
        "id": "vertical_velocity",
        "name": "Vertical Velocity (Omega)",
        "category": "Pressure & Atmosphere",
        "units": "Pa/s",
        "palette": "diverging_omega",
        "min": -1.2,
        "max": 1.2,
        "description": "Vertical pressure velocity (negative values indicate strong convective ascent).",
        "icon": "ArrowDownUp",
    },

    # 5. HUMIDITY & MOISTURE
    {
        "id": "relative_humidity",
        "name": "Relative Humidity",
        "category": "Humidity & Moisture",
        "units": "%",
        "palette": "humidity",
        "min": 10,
        "max": 100,
        "description": "Ratio of vapor pressure to saturation vapor pressure.",
        "has_levels": True,
        "icon": "Droplets",
    },
    {
        "id": "specific_humidity",
        "name": "Specific Humidity",
        "category": "Humidity & Moisture",
        "units": "g/kg",
        "palette": "humidity",
        "min": 1,
        "max": 22,
        "description": "Mass of water vapor per unit mass of moist air.",
        "icon": "Droplet",
    },
    {
        "id": "dew_point",
        "name": "Dew Point",
        "category": "Humidity & Moisture",
        "units": "°C",
        "palette": "thermal",
        "min": 5,
        "max": 30,
        "description": "Temperature at which air becomes saturated at constant pressure.",
        "icon": "Waves",
    },
    {
        "id": "precipitable_water",
        "name": "Precipitable Water (TPW)",
        "category": "Humidity & Moisture",
        "units": "kg/m²",
        "palette": "humidity",
        "min": 15,
        "max": 80,
        "description": "Total integrated atmospheric water vapor column.",
        "icon": "Container",
    },
    {
        "id": "moisture_transport",
        "name": "Moisture Transport (IVT)",
        "category": "Humidity & Moisture",
        "units": "kg/(m·s)",
        "palette": "humidity",
        "min": 100,
        "max": 1200,
        "description": "Integrated Vapor Transport from Arabian Sea across peninsular India.",
        "icon": "MoveRight",
    },
    {
        "id": "moisture_flux",
        "name": "Moisture Flux Convergence",
        "category": "Humidity & Moisture",
        "units": "g/(kg·s)",
        "palette": "diverging_rain",
        "min": -5,
        "max": 5,
        "description": "Horizontal convergence of water vapor driving convective rainfall.",
        "icon": "Minimize2",
    },

    # 6. CONVECTIVE / SEVERE
    {
        "id": "cape",
        "name": "CAPE",
        "category": "Convective & Severe",
        "units": "J/kg",
        "palette": "cape",
        "min": 0,
        "max": 4500,
        "description": "Convective Available Potential Energy for severe thunderstorm updrafts.",
        "icon": "Zap",
    },
    {
        "id": "cin",
        "name": "CIN",
        "category": "Convective & Severe",
        "units": "J/kg",
        "palette": "cin",
        "min": 0,
        "max": 250,
        "description": "Convective Inhibition capping inversion barrier.",
        "icon": "ShieldAlert",
    },
    {
        "id": "lifted_index",
        "name": "Lifted Index",
        "category": "Convective & Severe",
        "units": "K",
        "palette": "lifted_index",
        "min": -9,
        "max": 6,
        "description": "Thermal stability index (< -4 indicates severe instability).",
        "icon": "TrendingUp",
    },
    {
        "id": "k_index",
        "name": "K Index",
        "category": "Convective & Severe",
        "units": "°C",
        "palette": "convective",
        "min": 15,
        "max": 45,
        "description": "Thunderstorm potential based on vertical temperature lapse rate and moisture.",
        "icon": "BarChart2",
    },
    {
        "id": "total_totals",
        "name": "Total Totals Index",
        "category": "Convective & Severe",
        "units": "°C",
        "palette": "convective",
        "min": 35,
        "max": 60,
        "description": "Severe weather parameter combining 850hPa dewpoint and 500hPa temperature.",
        "icon": "PieChart",
    },
    {
        "id": "convective_prob",
        "name": "Convective Precipitation Prob",
        "category": "Convective & Severe",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Probability of deep convective cloud initiation.",
        "icon": "Percent",
    },
    {
        "id": "lightning_prob",
        "name": "Lightning Probability",
        "category": "Convective & Severe",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Probability of cloud-to-ground lightning discharge.",
        "icon": "ZapOff",
    },
    {
        "id": "severe_rain_prob",
        "name": "Severe Rainfall Probability",
        "category": "Convective & Severe",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Joint probability of heavy rain and severe convective updrafts.",
        "icon": "AlertTriangle",
    },

    # 7. CLOUDS & RADIATION
    {
        "id": "cloud_total",
        "name": "Total Cloud Cover",
        "category": "Clouds & Radiation",
        "units": "%",
        "palette": "cloud",
        "min": 0,
        "max": 100,
        "description": "Total fraction of sky covered by all cloud types.",
        "icon": "Cloud",
    },
    {
        "id": "cloud_low",
        "name": "Low Cloud Cover",
        "category": "Clouds & Radiation",
        "units": "%",
        "palette": "cloud",
        "min": 0,
        "max": 100,
        "description": "Stratus and stratocumulus boundary layer clouds.",
        "icon": "Cloud",
    },
    {
        "id": "cloud_mid",
        "name": "Mid Cloud Cover",
        "category": "Clouds & Radiation",
        "units": "%",
        "palette": "cloud",
        "min": 0,
        "max": 100,
        "description": "Altostratus and altocumulus clouds.",
        "icon": "Cloud",
    },
    {
        "id": "cloud_high",
        "name": "High Cloud Cover",
        "category": "Clouds & Radiation",
        "units": "%",
        "palette": "cloud",
        "min": 0,
        "max": 100,
        "description": "Cirrus and anvil blow-off clouds.",
        "icon": "Cloud",
    },
    {
        "id": "cloud_top_temp",
        "name": "Cloud-Top Temperature",
        "category": "Clouds & Radiation",
        "units": "°C",
        "palette": "infrared",
        "min": -75,
        "max": 25,
        "description": "Infrared brightness temperature of cloud tops (< -50°C indicates deep convection).",
        "icon": "Eye",
    },
    {
        "id": "visibility",
        "name": "Visibility",
        "category": "Clouds & Radiation",
        "units": "km",
        "palette": "visibility",
        "min": 1,
        "max": 40,
        "description": "Surface horizontal meteorological visibility.",
        "icon": "EyeOff",
    },
    {
        "id": "shortwave_rad",
        "name": "Shortwave Solar Radiation",
        "category": "Clouds & Radiation",
        "units": "W/m²",
        "palette": "solar",
        "min": 0,
        "max": 1000,
        "description": "Incident solar shortwave irradiance reaching the surface.",
        "icon": "SunMedium",
    },
    {
        "id": "longwave_rad",
        "name": "Longwave Radiation (OLR)",
        "category": "Clouds & Radiation",
        "units": "W/m²",
        "palette": "infrared",
        "min": 140,
        "max": 320,
        "description": "Top-of-atmosphere Outgoing Longwave Radiation.",
        "icon": "Radio",
    },

    # 8. MONSOON
    {
        "id": "monsoon_active_break",
        "name": "Active / Break Monsoon Index",
        "category": "Monsoon",
        "units": "Index",
        "palette": "monsoon_regime",
        "min": 0,
        "max": 100,
        "description": "Dynamic synoptic index evaluating active versus break monsoon conditions.",
        "icon": "Compass",
    },
    {
        "id": "monsoon_regime",
        "name": "Monsoon Regime Classification",
        "category": "Monsoon",
        "units": "Regime",
        "palette": "monsoon_regime",
        "min": 0,
        "max": 100,
        "description": "Synoptic regime identification (Active, Break, Normal, Onset, Withdrawal).",
        "icon": "Globe",
    },
    {
        "id": "monsoon_rain_anomaly",
        "name": "Monsoon Rainfall Anomaly",
        "category": "Monsoon",
        "units": "mm/day",
        "palette": "diverging_rain",
        "min": -25,
        "max": 35,
        "description": "Monsoon precipitation departure from long-period average.",
        "icon": "TrendingUp",
    },
    {
        "id": "monsoon_low_pressure_prob",
        "name": "Monsoon Low-Pressure Probability",
        "category": "Monsoon",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Probability of monsoon low-pressure system (LPS) formation.",
        "icon": "Disc",
    },
    {
        "id": "monsoon_depression_prob",
        "name": "Monsoon Depression Probability",
        "category": "Monsoon",
        "units": "%",
        "palette": "probability",
        "min": 0,
        "max": 100,
        "description": "Probability of monsoon depression intensification over Bay of Bengal.",
        "icon": "Target",
    },
    {
        "id": "monsoon_850_circulation",
        "name": "850 hPa Monsoon Circulation",
        "category": "Monsoon",
        "units": "m/s",
        "palette": "wind_jet",
        "min": 0,
        "max": 30,
        "description": "Cross-equatorial Somali Jet flow into Indian subcontinent.",
        "icon": "Navigation2",
    },
    {
        "id": "olr_anomaly",
        "name": "OLR Convective Anomaly",
        "category": "Monsoon",
        "units": "W/m²",
        "palette": "infrared",
        "min": -60,
        "max": 60,
        "description": "Outgoing Longwave Radiation anomaly diagnosing active convective clusters.",
        "icon": "Radio",
    },

    # 9. ENSEMBLE & UNCERTAINTY
    {
        "id": "ensemble_mean",
        "name": "Ensemble Mean",
        "category": "Ensemble & Uncertainty",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 120,
        "description": "21-member ensemble arithmetic mean forecast.",
        "icon": "Cpu",
    },
    {
        "id": "ensemble_spread",
        "name": "Ensemble Spread (Std Dev)",
        "category": "Ensemble & Uncertainty",
        "units": "mm/day",
        "palette": "uncertainty",
        "min": 0,
        "max": 35,
        "description": "Standard deviation across all 21 ensemble members indicating forecast uncertainty.",
        "icon": "Activity",
    },
    {
        "id": "ensemble_range",
        "name": "Ensemble Range (Max - Min)",
        "category": "Ensemble & Uncertainty",
        "units": "mm/day",
        "palette": "uncertainty",
        "min": 0,
        "max": 90,
        "description": "Spread between minimum and maximum ensemble realizations.",
        "icon": "Sliders",
    },
    {
        "id": "ensemble_p10",
        "name": "Ensemble P10 (10th Percentile)",
        "category": "Ensemble & Uncertainty",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 50,
        "description": "10% non-exceedance probability dry bound.",
        "icon": "ChevronDown",
    },
    {
        "id": "ensemble_p25",
        "name": "Ensemble P25 (Lower Quartile)",
        "category": "Ensemble & Uncertainty",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 75,
        "description": "25th percentile ensemble member.",
        "icon": "ChevronDown",
    },
    {
        "id": "ensemble_p50",
        "name": "Ensemble P50 (Median)",
        "category": "Ensemble & Uncertainty",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 100,
        "description": "50th percentile ensemble median forecast.",
        "icon": "Minus",
    },
    {
        "id": "ensemble_p75",
        "name": "Ensemble P75 (Upper Quartile)",
        "category": "Ensemble & Uncertainty",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 125,
        "description": "75th percentile ensemble member.",
        "icon": "ChevronUp",
    },
    {
        "id": "ensemble_p90",
        "name": "Ensemble P90 (90th Percentile)",
        "category": "Ensemble & Uncertainty",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 160,
        "description": "90th percentile ensemble tail wet risk bound.",
        "icon": "ChevronUp",
    },

    # 10. AI POST-PROCESSING
    {
        "id": "raw_forecast",
        "name": "Raw Model Forecast",
        "category": "AI Post-Processing",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 150,
        "description": "Raw uncalibrated NWP precipitation output from physics model.",
        "icon": "Server",
    },
    {
        "id": "ai_postprocessed",
        "name": "AI Post-Processed Forecast",
        "category": "AI Post-Processing",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 150,
        "description": "Regime-aware neural/XGBoost post-processed precipitation forecast.",
        "icon": "Sparkles",
    },
    {
        "id": "observed_reference",
        "name": "Observed / Reference Data",
        "category": "AI Post-Processing",
        "units": "mm/day",
        "palette": "rain",
        "min": 0,
        "max": 150,
        "description": "Ground truth verification data (ERA5 / IMD gauge network).",
        "icon": "CheckCircle2",
    },
    {
        "id": "forecast_bias",
        "name": "Forecast Bias (Raw - Observed)",
        "category": "AI Post-Processing",
        "units": "mm/day",
        "palette": "diverging_bias",
        "min": -40,
        "max": 40,
        "description": "Raw NWP systematic error and spatial bias.",
        "icon": "MinusCircle",
    },
    {
        "id": "corrected_bias",
        "name": "Corrected Bias (AI - Observed)",
        "category": "AI Post-Processing",
        "units": "mm/day",
        "palette": "diverging_bias",
        "min": -20,
        "max": 20,
        "description": "Residual error after AI regime-aware post-processing.",
        "icon": "CheckCircle",
    },
    {
        "id": "error_reduction",
        "name": "Error Reduction Skill (%)",
        "category": "AI Post-Processing",
        "units": "%",
        "palette": "skill_score",
        "min": 0,
        "max": 95,
        "description": "Percentage reduction in Mean Absolute Error achieved by AI post-processing.",
        "icon": "TrendingDown",
    },
    {
        "id": "uncertainty_field",
        "name": "Forecast Uncertainty Margin",
        "category": "AI Post-Processing",
        "units": "mm",
        "palette": "uncertainty",
        "min": 0,
        "max": 45,
        "description": "90% spatial confidence interval half-width.",
        "icon": "ShieldAlert",
    },
]


def get_all_categories() -> List[Dict[str, Any]]:
    """Return list of categories with their child layer items."""
    categories_dict: Dict[str, List[Dict[str, Any]]] = {}
    for layer in METEOROLOGICAL_LAYERS:
        cat = layer["category"]
        if cat not in categories_dict:
            categories_dict[cat] = []
        categories_dict[cat].append(layer)

    return [{"category": k, "layers": v, "count": len(v)} for k, v in categories_dict.items()]


def get_layer_metadata(layer_id: str) -> Dict[str, Any]:
    """Retrieve metadata for a specific layer."""
    for l in METEOROLOGICAL_LAYERS:
        if l["id"] == layer_id:
            return l
    # Default fallback
    return {
        "id": layer_id,
        "name": layer_id.replace("_", " ").title(),
        "category": "General",
        "units": "",
        "palette": "turbo",
        "min": 0,
        "max": 100,
        "description": "",
    }
